targets:
  $default:
    builders:
      generators|annotations:
        enabled: true
      json_serializable:
        options:
          # Add any additional options here if needed
          generate_to: lib/models

builders:
  generators:
    target: ":generators"
    import: "package:generators/generators.dart"
    builder_factories: ["generateJsonClass"] #Builder name(BuilderOptions)
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]